# Generated by Django 2.0.2 on 2018-02-22 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180222_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='creation date'),
        ),
    ]
